# -*- coding: utf-8 -*-
"""nlp_lab5_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/buzzaggwd/NLP/blob/main/nlp_lab5_2.ipynb
"""

import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import math

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.metrics import adjusted_rand_score, v_measure_score
from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt

nltk.download('stopwords')
nltk.download('wordnet')

PATH_TO_FILE: str = 'fake_news_dataset2.csv'

df = pd.read_csv(PATH_TO_FILE, encoding='utf-8')

print(df)

# p.s. датасет был ну очень огромный, пришлось обрезать до 500 строк, зато я могу его обработать🥲

lemmatizer = WordNetLemmatizer()
english_stopwords = stopwords.words('english')

# удаляем стоп-слова, делаем нижний регистр, разделяем слова
def preprocessing(texts: list[str]) -> list[list[str]]:
    processed = []
    for text in texts:
        clean_text = re.sub(r'[^a-z\s]', '', text.lower())
        words = clean_text.split()
        processed.append(words)
    return processed

processed_texts = preprocessing(df['text'].tolist())
print(processed_texts[10])

# лемматизация
def lemmatization(texts: list[list[str]]) -> list[list[str]]:
    lemmatized = []
    for sublist in texts:
        current_lemmas = []
        for word in sublist:
            if word not in english_stopwords:
                lemma = lemmatizer.lemmatize(word)
                current_lemmas.append(lemma)
        lemmatized.append(current_lemmas)
    return lemmatized

final_texts = lemmatization(processed_texts)
print(final_texts[10])

# векторизация
texts_for_vectorization = [' '.join(tokens) for tokens in final_texts]

# TF-IDF
vectorizer = TfidfVectorizer(max_features=1000)
X = vectorizer.fit_transform(texts_for_vectorization)
print("Матрица TF-IDF (размерность):", X.shape)

# кластеризация
n_clusters = df['category'].nunique()
kmeans = KMeans(n_clusters=n_clusters, random_state=42)
clusters = kmeans.fit_predict(X)

# сравнение с реальной разметкой
true_labels = df['category'].values
ari = adjusted_rand_score(true_labels, clusters)
v_measure = v_measure_score(true_labels, clusters)
print(f"Качество кластеризации:\nARI: {ari:.2f}\nV-measure: {v_measure:.2f}")

# выборки
X_train, X_test, y_train, y_test = train_test_split(X, true_labels, test_size=0.2, random_state=42, stratify=true_labels)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25, random_state=42, stratify=y_train)

print("Размеры выборок:")
print(f"Train: {X_train.shape[0]}, Val: {X_val.shape[0]}, Test: {X_test.shape[0]}")

plt.figure(figsize=(10, 6))
df['category'].value_counts().plot(kind='bar')
plt.title('Распределение категорий в датасете')
plt.xlabel('Категория новостей')
plt.ylabel('Количество новостей')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""---"""

import tensorflow as tf
print("Доступен GPU:", tf.config.list_physical_devices('GPU'))

os.environ["WANDB_DISABLED"] = "true"

!pip install evaluate

!pip install --upgrade transformers datasets

import numpy as np
import torch
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from transformers import (
    DistilBertForSequenceClassification,
    DistilBertTokenizer,
    Trainer,
    TrainingArguments
)
from datasets import Dataset
import os
import evaluate

accuracy_metric = evaluate.load("accuracy")
f1_metric = evaluate.load("f1")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return {
        "accuracy": accuracy_metric.compute(predictions=predictions, references=labels)["accuracy"],
        "f1": f1_metric.compute(predictions=predictions, references=labels, average="weighted")["f1"]
    }

le = LabelEncoder()
df['label'] = le.fit_transform(df['category'])

train_df, temp_df = train_test_split(df, test_size=0.2, random_state=42, stratify=df['label'])
val_df, test_df = train_test_split(temp_df, test_size=0.5, random_state=42, stratify=temp_df['label'])

train_dataset = Dataset.from_pandas(train_df[['text', 'label']])
val_dataset = Dataset.from_pandas(val_df[['text', 'label']])
test_dataset = Dataset.from_pandas(test_df[['text', 'label']])

tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

def tokenize_function(examples):
    return tokenizer(
        examples['text'],
        padding='max_length',
        truncation=True,
        max_length=256
    )

tokenized_train = train_dataset.map(tokenize_function, batched=True)
tokenized_val = val_dataset.map(tokenize_function, batched=True)
tokenized_test = test_dataset.map(tokenize_function, batched=True)

model = DistilBertForSequenceClassification.from_pretrained(
    'distilbert-base-uncased',
    num_labels=len(le.classes_)
)

training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    logging_steps=50,
    save_steps=500,
    learning_rate=2e-5,
    weight_decay=0.01
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_val,
    compute_metrics=compute_metrics
)

print("Начало обучения...")
trainer.train()

print("Тестирование модели...")
test_results = trainer.evaluate(tokenized_test)

print("Результаты на тестовой выборке:")
print(f"Loss: {test_results['eval_loss']:.3f}")
print(f"Accuracy: {test_results['eval_accuracy']:.3f}")
print(f"F1-Score: {test_results['eval_f1']:.3f}")

device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)

sample_text = test_df.iloc[0]['text']
inputs = tokenizer(
    sample_text,
    return_tensors="pt",
    truncation=True,
    max_length=256
).to(device)

outputs = model(**inputs)
predicted_label = le.inverse_transform(
    [np.argmax(outputs.logits.detach().cpu().numpy())]
)
print(f"Пример предсказания: {predicted_label}")
print(f"Истинная метка: {test_df.iloc[0]['category']}")

"""Так, ну теперь выводы. Что-то мне подсказывает, что мы имеем низкое качество модели. Accuracy (18%) и F1-Score (5.5%) совсем небольшие, что говорит что модель практически не способна правильно классифицировать новости.

Предсказание "Business" вместо "Sports" показывает, что модель не улавливает смысловые различия между категориями.

Возможно (точнее скорее всего) у нас такая неумная модель из-за урезанного датасета, но я не могла взять больше, у меня тупо умирал коллаб.. Получилось всего 500 примеров на 7 классов (~70 на класс) модели сложно выявить паттерны.
"""